package com.gamezone.model;

import java.time.LocalDate;

public class Return extends product {

    private string devolution;
    private LocalDate date;
    private List<Product> products;
    private string reason_for_return;
    private double mount_return;




















     /**
     * @return the platform the game was developed for
     */
    public String getdevolution() {
        return devolution;
    }

    /**
     * @return the genre of the game
     */
    public LocalDate getDate() {
        return date;
    }

    /**
     * @return the genre of the game
     */
    public List<Product> getProducts() {
        return products;
    }

    /**
     * @return the genre of the game
     */
    public String getreason_for_return() {
        return reason_for_return;
    }

    /**
     * @return the genre of the game
     */
    public double getmount_return() {
        return mount_return;
    }

/** ver si ya subio, esta es la parte que tengo, revisen, aun faltan algunos atributos
     */ no quiero subirse
}